import { Inter } from "next/font/google";

import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeicons/primeicons.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Los inmaduros roller Madrid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-slate-900 to-slate-700`}
      >
        {children}
      </body>
    </html>
  );
}
