import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeicons/primeicons.css";
import { PrimeReactProvider } from "primereact/api";
import RoutersContextProvider from "@/context/RoutesContext";
import FormCallRouteContextProvider from "@/context/FormCallRouteContext";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Los inmaduros roller Madrid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <RoutersContextProvider>
          <FormCallRouteContextProvider>
            <PrimeReactProvider>
              <body
                className={`${inter.className} bg-gradient-to-r from-slate-900 to-slate-700`}
              >
                <Navbar />

                {children}
                <Footer />
              </body>
            </PrimeReactProvider>
          </FormCallRouteContextProvider>
        </RoutersContextProvider>
      </html>
    </ClerkProvider>
  );
}
