import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import { PrimeReactProvider } from "primereact/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Los inmaduros roller Madrid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </PrimeReactProvider>
    </html>
  );
}
