const routes = [
  {
    name: "Héroes",
    image: "",
    approximateDistance: "20 km",
    description:
      "Ruta muy disfrutable, con muchos kilómetros de suave bajada, hasta llegar a cuesta de la vega, donde la cosa se pone interesante.",
    map: "",
    reviews: [],
  },
  {
    name: "Súper héroes",
    image: "",
    approximateDistance: "25 km",
    description:
      "Ideal para patinadores con experiencia, ya que requiere buen control de los patines y habilidad para frenar en zonas de tráfico. Disfruta de una mezcla de paisajes urbanos mientras desafías tu técnica.",
    map: "",
    reviews: [],
  },
  {
    name: "Clásica",
    image: "",
    approximateDistance: "24 km",
    description:
      "La ruta discurre por asfalto, se recomiendan protecciones y luces. Cada uno es responsable de su seguridad.",
    map: "",
    reviews: [],
  },
  {
    name: "Queen",
    image: "",
    approximateDistance: "15 km",
    description: "Esta ruta mezcla tramos de carril bici y carretera, diseñada para patinadores con experiencia intermedia. Es ideal para pasar un buen rato, combinando la tranquilidad del carril bici con la emoción de la carretera, requiriendo cierta autonomía y habilidad para mantener el control en diferentes entornos.",
    map: "",
    reviews: [],
  },
  {
    name: "El calamar",
    image: "",
    approximateDistance: "15 km",
    description: "Explora las calles de Madrid en una ruta que combina el placer de callejear con una parada deliciosa en el Palacio Real para disfrutar de un bocadillo de calamares. Una experiencia completa para patinadores con autonomía, antes de continuar el recorrido.",
    map: "",
    reviews: [],
  },
  {
    name: "Arcade",
    image: "",
    approximateDistance: "18 km",
    description: "Una ruta de mayor distancia diseñada para patinadores con autonomía y confianza en carretera. Toda la ruta transcurre por asfalto, lo que permite un patinaje fluido y sostenido. Recomendado para quienes buscan velocidad y adrenalina en un entorno urbano.",
    map: "https://www.google.com/maps/d/u/3/embed?mid=1jn_UxYOYkPzZAjzy4bRJSZTOrlUtG6w&ehbc=2E312F&noprof=1",
    reviews: [],
  },
  {
    name: "Anillo ciclista",
    image: "",
    approximateDistance: "55 km",
    description:
      "Ruta de larga distancia por carril bici, para los patinadores con más fondo. Vuelta completa al anillo ciclista de Madrid.",
    map: "",
    reviews: [],
  },
  {
    name: "La leyenda",
    image: "",
    approximateDistance: "25 km",
    description: "Una emocionante ruta por carretera que incluye los mejores túneles de la ciudad. Perfecta para patinadores con control en bajadas y búsqueda de adrenalina. Disfruta de la velocidad en un entorno único, ideal para quienes tienen autonomía total sobre sus patines.",
    map: "leyenda.gpx",
    reviews: [],
  },
  {
    name: "Vladi",
    image: "",
    approximateDistance: "24 km",
    description: "Una ruta de mayor distancia diseñada para patinadores con autonomía y confianza en carretera. Toda la ruta transcurre por asfalto, lo que permite un patinaje fluido y sostenido. Recomendado para quienes buscan velocidad y adrenalina en un entorno urbano.",
    map: "",
    reviews: [],
  },
  {
    name: "Las perseidas",
    image: "",
    approximateDistance: "30 km",
    description: "Desde el helipuerto de Morata de Tajuña hasta Arganda del Rey, esta ruta de 30 km aproximadamente por carril bici es ideal para disfrutar de la noche y la lluvia de Perseidas. Requiere resistencia y buen ritmo, además de luz propia, ya que la oscuridad total acompaña el trayecto.",
    map: "",
    reviews: [],
  },
  {
    name: "Dora",
    image: "",
    approximateDistance: "19 km",
    description: "Diseñada para patinadores con fondo y resistencia, esta ruta por carretera desafía con buenas subidas y premia con emocionantes bajadas. Requiere autonomía completa para disfrutar al máximo de este recorrido exigente.",
    map: "",
    reviews: [],
  },
  {
    name: "Caracolera",
    image: "",
    approximateDistance: "12 km",
    description:
      "Ruta apta para niños y todo aquel que tenga ganas de divertirse. Se hace a ritmo tranquilo y se ayudará a quien lo necesite en las bajadas. Se hacen paradas para reagrupar y beber agua. Recomendamos llevar protecciones, casco y agua.",
    map: "https://www.google.com/maps/d/u/3/embed?mid=1cBsMyC0Dp-fURJvEatHCKnvI17KfiHw&ehbc=2E312F&noprof=1",
    reviews: [],
  },
  {
    name: "Caracolera central",
    image: "",
    approximateDistance: "14 km",
    description:
      "Una ruta ideal para niños y cualquier persona con ganas de divertirse, recorriendo el centro de Madrid a un ritmo tranquilo. Se ofrecen paradas para reagrupamiento y beber agua, con apoyo en las bajadas para quienes lo necesiten. Es recomendable llevar protecciones, casco y agua para disfrutar con seguridad.",
    map: "",
    reviews: [],
  },
  {
    name: "los 40",
    image: "",
    approximateDistance: "15 km",
    description: "Esta ruta de distancia media combina carril bici y tramos de carretera. Ideal para patinadores con experiencia, ya que requiere buen control de los patines y habilidad para frenar en zonas de tráfico. Disfruta de una mezcla de paisajes urbanos mientras desafías tu técnica.",
    map: "",
    reviews: [],
  },
  {
    name: "Los poblados",
    image: "",
    approximateDistance: "12 km",
    description: "Esta ruta sigue exclusivamente el carril bici, perfecta para un patinaje relajado pero continuo. Ideal para disfrutar del entorno mientras mantienes un buen ritmo, sin preocuparte por el tráfico vehicular.",
    map: "poblados.gpx",
    reviews: [],
  },
  {
    name: "La horchata",
    image: "",
    approximateDistance: "16 km",
    description: "Una ruta urbana por carretera pensada para disfrutar del entorno mientras callejeas. Perfecta para explorar la ciudad a un ritmo relajado, con una parada estratégica para saborear una refrescante horchata antes de continuar la aventura sobre ruedas.",
    map: "",
    reviews: [],
  },
  {
    name: "Excalibur",
    image: "",
    approximateDistance: "18 km",
    description: "Inspirada en la leyenda del Rey Arturo, esta ruta comienza con 18 km de desafío entre calles y cuestas, donde sudarás la camiseta. Los últimos 9 km ofrecen suelo más liso y bajadas suaves, perfectas para quienes quieran unirse en el metro Oporto. Ideal para patinadores de nivel medio-bajo que prefieren evitar cuestas, tráfico, o terrenos difíciles.",
    map: "",
    reviews: [],
  },
  {
    name: "Mutantes",
    image: "",
    approximateDistance: "",
    description: " Inspirada en los héroes mutantes, esta ruta por carretera permite un ritmo tranquilo y constante. Se recomiendan protecciones para disfrutar con seguridad. Incluye dos paradas estratégicas para recuperar fuerzas, ideal para patinadores con autonomía que buscan un recorrido relajado.",
    map: "",
    reviews: [],
  },
];
