const routes = [
  {
    name: "Héroes",
    images: "",
    approximateDistance: "",
    description:
      "Ruta muy disfrutable, con muchos kilómetros de suave bajada, hasta llegar a cuesta de la vega, donde la cosa se pone interesante.",
    map: "",
    reviews: [],
  },
  {
    name: "Súper héroes",
    images: "",
    approximateDistance: "22 km",
    description:
      "Se recomiendan protecciones e iluminación. Cada uno es responsable de su seguridad.",
    map: "",
    reviews: [],
  },
  {
    name: "Clásica",
    images: "",
    approximateDistance: "24 km",
    description:
      "La ruta discurre por asfalto, se recomiendan protecciones y luces. Cada uno es responsable de su seguridad.",
    map: "",
    reviews: [],
  },
  {
    name: "Queen",
    images: "",
    approximateDistance: "15 km",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "El calamar",
    images: "",
    approximateDistance: "",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Arcade",
    images: "",
    approximateDistance: "24 km",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Anillo ciclista",
    images: "",
    approximateDistance: "55 km",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "La leyenda",
    images: "",
    approximateDistance: "",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Vladi",
    images: "",
    approximateDistance: "24 km",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Las perseidas",
    images: "",
    approximateDistance: "",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Dora",
    images: "",
    approximateDistance: "18 km",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Caracolera",
    images: "",
    approximateDistance: "14 km",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Caracolera central",
    images: "",
    approximateDistance: "",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "los 40",
    images: "",
    approximateDistance: "",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Los poblados",
    images: "",
    approximateDistance: "",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "La horchata",
    images: "",
    approximateDistance: "",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Excalibur",
    images: "",
    approximateDistance: "18 km",
    description: "",
    map: "",
    reviews: [],
  },
  {
    name: "Mutantes",
    images: "",
    approximateDistance: "",
    description: "",
    map: "",
    reviews: [],
  },

];
